schema_version = "0.3"
material_id = "intervaltree-57bfb4-1bc406e1"
catalog = "catalog/repo-materials.toml"
material_path = "materials/intervaltree-57bfb4-1bc406e1"
repository_url = "https://github.com/chaimleib/intervaltree"
base_commit = "1bc406e1f441577c4e421fc51aba2ab67fbd97fb"
source_tree = "bb66f069ef054d7ca84dba285e83d59563e013da"
environment_sha256 = "461fb57432cddc3c5d73f2a647739b71620bda8e1e163abb9df240dade0ad94a"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "nwrneztpg9l1mr8qzswf"
template_alias = "alv-intervaltree-57bfb4-1bc406e1-v2-env-461fb574"
operational_dependency = false
