schema_version = "0.3"
material_id = "aws-lambda-web-adapter-9ca7a5-34d3a299"
catalog = "catalog/repo-materials.toml"
material_path = "materials/aws-lambda-web-adapter-9ca7a5-34d3a299"
repository_url = "https://github.com/aws/aws-lambda-web-adapter"
base_commit = "34d3a29939ea0c387c145f67cbd7ad72ae833c71"
source_tree = "2bd69b774b7aa54e8dd1cf2add5383f9df0d7f58"
environment_sha256 = "194e950e2d7949070609370117d88d135a80735ff94d53f9e7c1d4294d63cdff"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "s1yueviiyvnf08zafrju"
template_alias = "alv-aws-lambda-web-adapt-9ca7a5-34d3a299-v2-env-65f4a9ce"
operational_dependency = false
