schema_version = "0.3"
material_id = "cargo-crev-b1e08a-fb944fe9"
catalog = "catalog/repo-materials.toml"
material_path = "materials/cargo-crev-b1e08a-fb944fe9"
repository_url = "https://github.com/crev-dev/cargo-crev"
base_commit = "fb944fe955ab451f0a339636ea140eebd1a83608"
source_tree = "1d86cc0cb4ff8383828b78065e0e66a07965b2a0"
environment_sha256 = "b4a6005dad01bcc3e8d951f87e2ddc19e932e4aa8379fcf65c3d052e697632f3"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "abvl8ofgu45pebj9jzln"
template_alias = "alv-cargo-crev-b1e08a-fb944fe9-v2-env-8ac01ba1"
operational_dependency = false
