schema_version = "0.3"
material_id = "nmrs-c24d93-c51da7d4"
catalog = "catalog/repo-materials.toml"
material_path = "materials/nmrs-c24d93-c51da7d4"
repository_url = "https://github.com/freedesktop-rs/nmrs"
base_commit = "c51da7d4eadb5dabf987a31ce5595d17738e5915"
source_tree = "c38c7dde07b171d0e5dbe291c8cf3e1ba528ae51"
environment_sha256 = "712ef02d71d6d1fe0e5d7038a2488497f417c1321ddb92d80be70e4377c3e27d"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "041sn1yyjropbydmdzek"
template_alias = "alv-nmrs-c24d93-c51da7d4-v2-env-c7aade04"
operational_dependency = false
