schema_version = "0.3"
material_id = "cargo-zigbuild-4a8cac-0d2d958f"
catalog = "catalog/repo-materials.toml"
material_path = "materials/cargo-zigbuild-4a8cac-0d2d958f"
repository_url = "https://github.com/rust-cross/cargo-zigbuild"
base_commit = "0d2d958f87be99a5fbb7b3d05fd90931d24103f0"
source_tree = "a216ba2a591d37fae8ce0510d894c3d5776b4746"
environment_sha256 = "238bfedf68d6b77db7091159258cbf20b2ae19630f7684212b6619ce47ede6b7"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "mfztd2ekz0uyqm650enx"
template_alias = "alv-cargo-zigbuild-4a8cac-0d2d958f-v2-env-a767b11a"
operational_dependency = false
