schema_version = "0.3"
material_id = "terraform-provider-fastl-3bce6c-5a0bac50"
catalog = "catalog/repo-materials.toml"
material_path = "materials/terraform-provider-fastl-3bce6c-5a0bac50"
repository_url = "https://github.com/fastly/terraform-provider-fastly"
base_commit = "5a0bac50e0a57c8bbf470f05ddef8319b4ad0314"
source_tree = "9cb849ac51facbf525a1b0cbc51afa0b3f3d68cf"
environment_sha256 = "41f89b9ab61e0caa0c12d48da272010272f12c8419303214fedd32986e8e1b24"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "k79w2jxjj3y2h97dl8yi"
template_alias = "alv-terraform-provider-f-3bce6c-5a0bac50-v2-env-41f89b9a"
operational_dependency = false
