schema_version = "0.3"
material_id = "rust-peg-0ce89b-3453b34e"
catalog = "catalog/repo-materials.toml"
material_path = "materials/rust-peg-0ce89b-3453b34e"
repository_url = "https://github.com/kevinmehall/rust-peg"
base_commit = "3453b34e8dcf0482c650f917e60d43ed944a71e2"
source_tree = "f73397e06248270905ef8b4fc2b72ab6238839ef"
environment_sha256 = "8683a9d24230f3c4494e40e736fe36f125fd942e61513c7377237b6515ab9030"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "ex008ev85gkb7g9l0mrv"
template_alias = "alv-rust-peg-0ce89b-3453b34e-v2-env-8683a9d2"
operational_dependency = false
