# Harbor envelope v2
# Source E2B template: alvance-repo-kube-vip-kube-vip-0d248ba40f-998a62a238-v12
# This file is an immutable Harbor fingerprint; do not force-build it.
FROM e2bdev/base
USER root
WORKDIR /app
