schema_version = "0.3"
material_id = "hotstuff-023abd-3179c6e6"
catalog = "catalog/repo-materials.toml"
material_path = "materials/hotstuff-023abd-3179c6e6"
repository_url = "https://github.com/relab/hotstuff"
base_commit = "3179c6e62929294961acbfd9bf8445769716a121"
source_tree = "5b13da0499f3233c71af729bf9b1ab5ae289f35c"
environment_sha256 = "58f7994d33348e39a5d79e6e35023b8f75133cf1f77a09cd383c622364ef64a6"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "lwigmi1of31n6rd6nid8"
template_alias = "alv-hotstuff-023abd-3179c6e6-v2-env-33b12a5f"
operational_dependency = false
