# Harbor envelope v2
# Source E2B template: alvance-repo-eslint-b52bd815-e34a0fa0ca-b539688a94-c1-m1024-v17
# This file is an immutable Harbor fingerprint; do not force-build it.
FROM e2bdev/base
USER root
WORKDIR /app
