schema_version = "0.3"
material_id = "libz-sys-39fce7-7ceb9154"
catalog = "catalog/repo-materials.toml"
material_path = "materials/libz-sys-39fce7-7ceb9154"
repository_url = "https://github.com/rust-lang/libz-sys"
base_commit = "7ceb9154052e9bf5944be78e0e08f2d1b8eaae9b"
source_tree = "73a46ecd385f227d539e23a5ef6a7df74e2d3aa3"
environment_sha256 = "5a2420e77ce5747e79b928b8b90e46f74cc529b7598ef682b2be68e082599ed1"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "jp1l4l063qynf3nxf7ef"
template_alias = "alv-libz-sys-39fce7-7ceb9154-v2-env-ad74c1be"
operational_dependency = false
