schema_version = "0.3"
material_id = "cassandra-gocql-driver-42961e-00fc2909"
catalog = "catalog/repo-materials.toml"
material_path = "materials/cassandra-gocql-driver-42961e-00fc2909"
repository_url = "https://github.com/apache/cassandra-gocql-driver"
base_commit = "00fc2909c64a7529fe49fb31b0fa8662342ebe69"
source_tree = "d659e8dddb24b35dc8f9b2ce3c8c501291c1fd93"
environment_sha256 = "6b8dc66d6b170343e8c65dead045a4c65a977b5865caabf59c111bc3cf5dcc45"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "xhh2r1xp2i3xqiqsw56j"
template_alias = "alv-cassandra-gocql-driv-42961e-00fc2909-v2-env-aa949532"
operational_dependency = false
