schema_version = "0.3"
material_id = "mysqld-exporter-5bb1ba-2a385072"
catalog = "catalog/repo-materials.toml"
material_path = "materials/mysqld-exporter-5bb1ba-2a385072"
repository_url = "https://github.com/prometheus/mysqld_exporter"
base_commit = "2a3850727e5af11873cc715a2b1a31bedce264eb"
source_tree = "3c83f4f7d9c317ac3ea9a5cd05c4c7e845edd7dc"
environment_sha256 = "94951aa57d5dd1bf5076919a476168f771f31540bbe3e4935e1ce54fd420a9dd"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "irrt4oaki6z2lcvx2qsj"
template_alias = "alv-mysqld-exporter-5bb1ba-2a385072-v2-env-68317c5d"
operational_dependency = false
