schema_version = "0.3"
material_id = "seccompiler-84db25-c05f2079"
catalog = "catalog/repo-materials.toml"
material_path = "materials/seccompiler-84db25-c05f2079"
repository_url = "https://github.com/rust-vmm/seccompiler"
base_commit = "c05f20798917d8df814d1154aea3135a53f7f944"
source_tree = "7842cc3636fec41cbacc3ffdbebfec1fd82449bb"
environment_sha256 = "6f1c0552cde72cfe1d04811a1225344f766bdfd854963a724ad704341c389769"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "fs0zf0qs2dwzk6tqwi17"
template_alias = "alv-seccompiler-84db25-c05f2079-v2-env-3396d5e7"
operational_dependency = false
