schema_version = "0.3"
material_id = "aws-nuke-593db9-bfe693f1"
catalog = "catalog/repo-materials.toml"
material_path = "materials/aws-nuke-593db9-bfe693f1"
repository_url = "https://github.com/ekristen/aws-nuke"
base_commit = "bfe693f12ccfb324ef49cf4093994cec6bd6754b"
source_tree = "3c6159a42b751e99aea1b297e3bcf42f9a0004a8"
environment_sha256 = "0145cb5915f8d64a31f217e1788abaa1ee86a8a06f3c86476776074223f2a0c3"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "7bs3sqyf8cwmswmfbaii"
template_alias = "alv-aws-nuke-593db9-bfe693f1-v2-env-a0080682"
operational_dependency = false
