schema_version = "0.3"
material_id = "rust-minidump-b32ba9-0155eaf7"
catalog = "catalog/repo-materials.toml"
material_path = "materials/rust-minidump-b32ba9-0155eaf7"
repository_url = "https://github.com/rust-minidump/rust-minidump"
base_commit = "0155eaf70114f5ed3cbb172968eceaf6106940f7"
source_tree = "3356356605b9109fc2c5a53a13b93cfd826f2b9d"
environment_sha256 = "97596502ee502b374250fc120d3c07471ae7804e79f0eb555b15096745ffd89a"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "ha9c9ystnnbwowevd7w4"
template_alias = "alv-rust-minidump-b32ba9-0155eaf7-v2-env-97596502"
operational_dependency = false
