schema_version = "0.3"
material_id = "folderify-1259b7-4705f42b"
catalog = "catalog/repo-materials.toml"
material_path = "materials/folderify-1259b7-4705f42b"
repository_url = "https://github.com/lgarron/folderify"
base_commit = "4705f42b946ac7950c0431f0b0f39e9d6811a3fe"
source_tree = "008cf4105cbcf97c52b93ff5f3f6e39d214b216e"
environment_sha256 = "715bb27131a8451487fc7525247ecd8f21db580134ed19e9dcc84b68666c117f"
dockerfile_rebuildable = true
rebuild_network_required = true

[e2b_history]
template_id = "xp2x2gkse5iu5aed6uja"
template_alias = "alv-folderify-1259b7-4705f42b-v2-env-715bb271"
operational_dependency = false
